### ISSUE TITLE
Node version update

### ISSUE THREAD

**Issue by jean-baptisteb** [nickofthyme/object-remap#18]
Hello,

First of all, congratulation for this very usefull github actions ; you saved me a lot of time & test , this solution is very simple

I see latest commit are dated, and currently using your action trigger warning on github ; even if it works perfectly 

The following actions use a deprecated Node.js version and will be forced to run on node20: nickofthyme/object-remap@v2.0.0. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

It would be great if you have time to update it.

Regards

**Comment by nickofthyme** [comment]
Hey @jean-baptisteb

Thanks, I'm glad people have found it useful!

Yeah I can look at upgrading it to version `20` in the next few days.

**Comment by nickofthyme** [comment]
Ok that should do the trick. It could use a bit of an update but I don't have the time for that right now. For now I errored on the side of caution and touched very little to avoid breaking anything.

Let me know if you notice any issues and I can look into them. Thanks again for the ping!

**Comment by jean-baptisteb** [comment]
thank you very much for your rapidity !
just tested it, working without issue, nor more github warning linked to node version.
